//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MandhegParkingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingData
    {
        public int id { get; set; }
        public string license_plate { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public int employee_id { get; set; }
        public int hourly_rates_id { get; set; }
        public System.DateTime datetime_in { get; set; }
        public System.DateTime datetime_out { get; set; }
        public decimal amount_to_pay { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> last_updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual HourlyRate HourlyRate { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
